// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRX5xhHgM6yxRuZNh14DXBdokPfZ0ftM',
    appId: '1:28851727754:web:ce3f39635407b22301ec73',
    messagingSenderId: '28851727754',
    projectId: 'taskappfirebase-4fa90',
    authDomain: 'taskappfirebase-4fa90.firebaseapp.com',
    storageBucket: 'taskappfirebase-4fa90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJjFYWGzYyO3VvB8kzOAj_smBoLqkTR3E',
    appId: '1:28851727754:android:f5ea68ab5cb3bd4c01ec73',
    messagingSenderId: '28851727754',
    projectId: 'taskappfirebase-4fa90',
    storageBucket: 'taskappfirebase-4fa90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzADLkKFYZ9iVgfP6kT-FLCiwj8lfT8aQ',
    appId: '1:28851727754:ios:a5cfa20c5a64db8e01ec73',
    messagingSenderId: '28851727754',
    projectId: 'taskappfirebase-4fa90',
    storageBucket: 'taskappfirebase-4fa90.appspot.com',
    iosBundleId: 'com.example.taskappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzADLkKFYZ9iVgfP6kT-FLCiwj8lfT8aQ',
    appId: '1:28851727754:ios:195de98cfe806aaa01ec73',
    messagingSenderId: '28851727754',
    projectId: 'taskappfirebase-4fa90',
    storageBucket: 'taskappfirebase-4fa90.appspot.com',
    iosBundleId: 'com.example.taskappfirebase.RunnerTests',
  );
}
